config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    # No need for app/views/articles/update.html.erb
    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="edit-container">
  <h1>Edit Article</h1>
  <%= form_for(@article) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.submit %>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="card">
      <div class="title">
        <h3 class="card-title"><%= link_to article.title, article_path(article) %></h3>
      </div>
      <p class="card-text"><%= article.content %></p>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="new-article">
  <h1>New Article</h1>
  <%= form_for(@article) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.submit %>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="article">
  <div class="article-title">
    <h1 id="title"><%= @article.title %></h1>
    <a href="/articles/<%= @article.id %>/edit"><i class="fa-solid fa-pen-to-square"></i></a>
    <%= link_to "",
        article_path(@article),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
        class: "fa-solid fa-trash-can" %>
  </div>
  <div class="content">
    <p><%= @article.content %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <div class="banner">
      <%= link_to 'Wikinimous', articles_path, class: 'articles'%>
      <button class="btn btn-secondary" type="button" aria-haspopup="true" aria-expanded="false">
        <%= link_to 'New Article', new_article_path %>
      </button>
    </div>
    <%= yield %>
  </body>
</html>